[build]
  publish = "/"
  
# Headers for security and cache settings
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://cdnjs.cloudflare.com https://fonts.googleapis.com https://fonts.gstatic.com https://www.youtube.com https://formspree.io; script-src 'self' https://cdnjs.cloudflare.com 'unsafe-inline' 'unsafe-eval'; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; img-src 'self' data: https://via.placeholder.com; font-src 'self' https://fonts.gstatic.com; frame-src https://www.youtube.com https://formspree.io; connect-src 'self' https://formspree.io;"

# Override cache settings for HTML files
[[headers]]
  for = "*.html"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# CSS and JS can be cached for a day
[[headers]]
  for = "*.css"
    [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.js"
    [headers.values]
    Cache-Control = "public, max-age=86400"

# Add redirect for SPA and custom 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Form handling
[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true

# For Formspree integration
[[plugins]]
  package = "@netlify/plugin-emails"